name: Run checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  run-inheritance:
    runs-on: ubuntu-latest
    container: 
      image: python:3.7
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: python -m pip install -r requirements.txt
    - name: Run inheritance example
      run: python -m inheritance
    - name: Run mypy
      run: mypy inheritance

  run-composition:
    runs-on: ubuntu-latest
    container: 
      image: python:3.7
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: python -m pip install -r requirements.txt
    - name: Run composition example
      run: python -m composition
    - name: Run mypy
      run: mypy composition
